silverstripe/userhelp.silverstripe.org

app/_config/toolbar.yml, composer.json, composer.lock, themes/userhelp/templates/Includes/DocumentationHead.ss
added site header class
updated latest version of toolbar
set test and live urls for conf file
=> toolbar design update

.platform.yml, app/_config/docsviewer.yml, bin/update.sh, robots.txt
Also added robots file and updated url so docs are generated into assets folder
=> Added platform file and moved docs to assets

app/_config.php, app/_config/docsviewer.yml
@mandrew please check this works on your local and uat
=> Move lucene index into assets shared folder mount

app/code/UpdateTask.php
@assertchris can you have a look at this...
=> Clear the module before you clone it to ensure you get the latest markdown

README.md, app/code/RefreshMarkdownTask.php, app/code/UpdateDocsCronTask.php
(i) returned cron task name to UpdateDocsCronTask since this should only ever contain the tasks for refreshing the source md files and for reindexing them. 
(ii) tidied up README.md
=> Cleaning up

themes/userhelp/css/styles.css, themes/userhelp/templates/Layout/DocumentationViewer_DocumentationPage.ss
Also added error styling for form
=> added form styling for feedback form

.gitignore, app/_config/config.yml, app/code/ControllerExtension.php, composer.json, composer.lock, themes/userhelp/css/styles.css, themes/userhelp/templates/Layout/DocumentationViewer_DocumentationPage.ss
Helps us find out where to focus content efforts.
=> Adding a feedback tool to documentation

app/_config/docs-repositories.yml, app/_config/docsviewer.yml, themes/userhelp/templates/Includes/DocumentationVersions.ss
Content will still need a review.
=> Add 3.3 release branch

app/_config/docs-repositories.yml, app/_config/docsviewer.yml
Ready for 3.5 release. Merge and deploy.
=> Add 3.5 core version

app/_config/docs-repositories.yml, app/_config/docsviewer.yml, composer.json, composer.lock, themes/userhelp/css/styles.css, themes/userhelp/templates/Includes/DocumentationFooter.ss, themes/userhelp/templates/Includes/DocumentationHead.ss, themes/userhelp/templates/Includes/DocumentationVersions.ss
Also fixes CC logo alignment in footer
=> Add SS4 as stable default, add canonical URLs

composer.lock
Update to get latest docs-viewer updates on userhelp UAT.
=> Update docsviewer to 2.0.0-rc2

app/_config/docs-repositories.yml
Fixes https://github.com/silverstripe/userhelp.silverstripe.org/issues/52
=> DOCS Add required dependencies for ss3 user help

app/_config/docs-repositories.yml
Fixes to #59
Related https://github.com/silverstripe/silverstripe-userhelp-content/pull/90
=> DOCS Add sitewidecontent-report dependency

app/_config/docs-repositories.yml
WIP until we are ready to deploy SS4 docs to prod.
=> DOCS Readd user help content 4 for UAT

.gitignore, app/_config/docs-repositories.yml
Please wait to merge.
Relies on: https://github.com/silverstripe/silverstripe-userhelp-content/pull/113/files
=> Add new dependencies elemental and site summariser

app/_config/docs-repositories.yml
Relies on https://github.com/silverstripe/silverstripe-userhelp-content/pull/120
=> Add new dependency for share draft content

app/_config/docs-repositories.yml
**Hold off merging until elemental has been tagged to pull in master**
cc @ScopeyNZ
=> DOCS Update dependency for updated content block userhelp

app/_config/docs-repositories.yml
Relies on the updated PR for the symlinks: https://github.com/silverstripe/silverstripe-userhelp-content/pull/134
=> DOCS Update folder names to be consistent

app/_config/docs-repositories.yml
To be merged once CKAN registry has been tagged. cc @ScopeyNZ 
Relies on: https://github.com/silverstripe/silverstripe-userhelp-content/pull/133
=> DOCS Add repo dependency for CKAN registry

composer.lock
=> Update silverstripe/framework to 3.6.7

app/code/UpdateDocsCronTask.php
See #79 for more details. Commenting out so we can halt the content on the site until we figure out what the problem is.
=> DOCS Comment out refresh markdown task due to incorrectly pulling in repos

composer.json, composer.lock
Make it compat with PHP 7.3 and SS 3.7.
See https://github.com/silverstripe/doc.silverstripe.org/pull/186
=> Update dynamodb dep

app/_config/docs-repositories.yml
Adds MFA user help. See https://github.com/silverstripe/silverstripe-mfa/issues/217.
=> NEW Add silverstripe/mfa userguide to userhelp
